version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload 